language: ruby
gemfile: tests/Gemfile
rvm:
  - 1.9.3
before_install: sudo apt-get install vim-gtk
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: sh -c 'cd tests && bundle exec rake spec'
